package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// runContradictionsCheck is a lightweight LLM pass that scans recently-
// changed wiki articles for factual disagreements. Output goes to stdout
// (one finding per line) and also to wiki/_contradictions.md for Dream
// Phase 3 (Consolidate) to pick up. Does not auto-resolve.
//
// Uses the contextualize provider (cheap — typically Haiku or local
// gemma3:4b) because contradiction detection is pattern-matching over
// text, not reasoning. Also shares the provider abstraction so users on
// ollama pay zero.
//
// Invoked from `scribe lint --contradictions`. Keeps LintCmd's structural
// checks (frontmatter/size/orphans) and this LLM pass as distinct modes
// behind a single command.
func runContradictionsCheck(since string, limit int, dryRun bool, outputMD string) error {
	root, err := kbDir()
	if err != nil {
		return err
	}
	cfg := loadConfig(root)

	articles, err := collectArticlesForContradictionCheck(root, since, limit)
	if err != nil {
		return err
	}
	if len(articles) < 2 {
		logMsg("contradictions", "only %d article(s) in scope — need at least 2", len(articles))
		return nil
	}

	logMsg("contradictions", "checking %d article(s)", len(articles))
	if dryRun {
		for _, a := range articles {
			fmt.Println(" ", relPath(root, a))
		}
		return nil
	}

	// Build the prompt body inline; reuses the contextualize provider
	// abstraction so local/anthropic both work.
	var sb strings.Builder
	for _, a := range articles {
		data, err := os.ReadFile(a)
		if err != nil {
			continue
		}
		sb.WriteString("\n\n---\n\n### ")
		sb.WriteString(relPath(root, a))
		sb.WriteString("\n\n")
		sb.Write(data)
	}

	prompt, err := loadPrompt("contradictions.md", map[string]string{
		"ARTICLES": sb.String(),
	})
	if err != nil {
		return err
	}

	provider := newLLMProvider(
		cfg.Absorb.Contextualize.Provider,
		cfg.Absorb.Contextualize.Model,
		cfg.Absorb.Contextualize.OllamaURL,
		root,
	)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	text, err := provider.Generate(ctx, prompt)
	if err != nil {
		return fmt.Errorf("%s: %w", provider.Name(), err)
	}
	text = strings.TrimSpace(text)

	outPath := outputMD
	if outPath == "" {
		outPath = filepath.Join(root, "wiki", "_contradictions.md")
	}

	// If the LLM reports nothing, don't leave a pseudo-finding file on disk.
	// The review queue in `scribe status` keys off this file's existence;
	// keeping it around with "no contradictions found" inside would make
	// the queue misleading AND break `--resolve` with a silent no-op.
	if looksLikeNoContradictions(text) {
		_ = os.Remove(outPath)
		fmt.Println("no contradictions found")
		logMsg("contradictions", "clean — removed stale %s", relPath(root, outPath))
		return nil
	}

	header := fmt.Sprintf("# Contradictions — scanned %s\n\nGenerated by `scribe lint --contradictions`. Do not edit by hand; re-run to refresh.\n\n",
		time.Now().UTC().Format(time.RFC3339))
	_ = os.WriteFile(outPath, []byte(header+text+"\n"), 0o644)

	fmt.Println(text)
	logMsg("contradictions", "report written to %s", relPath(root, outPath))
	return nil
}

// looksLikeNoContradictions matches the output shapes LLMs use to say
// there's nothing to report. Being generous with phrasing because the
// prompt asks for a fixed sentinel but models improvise around it.
func looksLikeNoContradictions(s string) bool {
	s = strings.ToLower(strings.TrimSpace(s))
	return s == "" ||
		strings.Contains(s, "no contradictions found") ||
		strings.Contains(s, "no contradictions detected") ||
		strings.Contains(s, "no factual contradictions")
}

// collectArticlesForContradictionCheck walks the wiki dirs, filters by
// --since if given, and returns up to limit paths sorted by most-recently-
// modified first (most likely to contain drift).
func collectArticlesForContradictionCheck(root, since string, limit int) ([]string, error) {
	var cutoff time.Time
	if since != "" {
		d, err := time.ParseDuration(since)
		if err != nil {
			// Allow short-hand like "7d" via manual parse.
			if days, ok := strings.CutSuffix(since, "d"); ok {
				if n, err := time.ParseDuration(days + "h"); err == nil {
					d = n * 24
				}
			}
		}
		if d > 0 {
			cutoff = time.Now().Add(-d)
		}
	}

	type entry struct {
		path string
		mod  time.Time
	}
	var entries []entry
	err := walkArticles(root, func(path string, _ []byte) error {
		info, err := os.Stat(path)
		if err != nil {
			return nil //nolint:nilerr // skip unreadable, continue walk
		}
		if !cutoff.IsZero() && info.ModTime().Before(cutoff) {
			return nil
		}
		entries = append(entries, entry{path, info.ModTime()})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].mod.After(entries[j].mod) })
	if limit > 0 && len(entries) > limit {
		entries = entries[:limit]
	}
	out := make([]string, len(entries))
	for i, e := range entries {
		out[i] = e.path
	}
	return out, nil
}
