package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// DigestCmd regenerates wiki/_digest.md — the Renovate-dashboard
// pattern: a bot-maintained markdown dashboard committed inside the
// repo is the only governance UI git affords without a server. The
// digest is deterministic (no LLM) and derived ONLY from committed
// shared state (git history, articles), so every member's regeneration
// converges on the same content given the same history; it's in the
// derived-regenerable set, so pull conflicts on it auto-resolve.
// Per-machine state (pending approvals, the gitignored staleness and
// contradiction ledgers) prints to stdout only, never into the
// committed file — embedding it would make the digest a function of
// per-machine state and the regenerated bytes ping-pong between
// members' commits.
type DigestCmd struct {
	Days int `help:"Activity window in days." default:"7"`
}

func (c *DigestCmd) Run() error {
	root, err := kbDir()
	if err != nil {
		return err
	}
	cfg := loadConfig(root)

	content := buildDigest(root, cfg, c.Days)
	path := filepath.Join(root, "wiki", "_digest.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)

	// Machine-local addendum — meaningful only on THIS machine, so it
	// goes to the terminal, not into the shared file.
	if m, err := loadManifest(root); err == nil {
		if pending := m.pendingProjects(); len(pending) > 0 {
			fmt.Printf("note (this machine): %d project(s) pending approval — scribe projects review\n", len(pending))
		}
	}
	for _, n := range digestLocalNotes(root) {
		fmt.Printf("note (this machine): %s\n", n)
	}
	return nil
}

// digestLocalNotes renders findings from the gitignored staleness and
// contradiction ledgers. These exist (and differ) per machine — they
// must never enter the committed digest, or its bytes stop converging
// across members.
func digestLocalNotes(root string) []string {
	var notes []string
	if entries, err := readContradictionLedger(root); err == nil {
		open := 0
		for _, e := range entries {
			if e.ResolvedAt == "" {
				open++
			}
		}
		if open > 0 {
			notes = append(notes, fmt.Sprintf("%d unresolved contradiction(s) — `scribe contradictions list`", open))
		}
	}
	if entries, err := readStalenessLedger(root); err == nil && len(entries) > 0 {
		notes = append(notes, fmt.Sprintf("%d stale article(s) — `scribe stale list`", len(entries)))
	}
	return notes
}

// writeDigestFile regenerates the digest during sync. Errors are
// non-fatal — a digest failure must never block extraction or commit.
func writeDigestFile(root string, cfg *ScribeConfig) {
	content := buildDigest(root, cfg, 7)
	path := filepath.Join(root, "wiki", "_digest.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		logMsg("sync", "digest write failed: %v", err)
		return
	}
	logMsg("sync", "regenerated wiki/_digest.md")
}

// buildDigest renders the digest markdown.
func buildDigest(root string, cfg *ScribeConfig, days int) string {
	var b strings.Builder
	b.WriteString("# Team digest\n\n")
	b.WriteString("<!-- regenerated by `scribe digest` on every sync — do not edit by hand -->\n\n")
	fmt.Fprintf(&b, "Derived from committed history (window: %d days up to the last article commit). Conflicts on this file auto-resolve — it regenerates.\n", days)

	// --- Activity by contributor ---
	b.WriteString("\n## Activity\n\n")
	activity := gitDigestActivity(root, days)
	if len(activity) == 0 {
		b.WriteString("No article changes in the window.\n")
	}
	for _, a := range activity {
		fmt.Fprintf(&b, "- **%s** — %d new, %d updated\n", a.author, len(a.added), len(a.updated))
		for _, f := range capList(a.added, 8) {
			fmt.Fprintf(&b, "  - %s (new)\n", f)
		}
		for _, f := range capList(a.updated, 8) {
			fmt.Fprintf(&b, "  - %s (updated)\n", f)
		}
	}

	// --- Quality findings, routed to owners where a domain is known ---
	b.WriteString("\n## Quality findings\n\n")
	findings := 0

	if hits := findConflictMarkers(root); len(hits) > 0 {
		findings += len(hits)
		fmt.Fprintf(&b, "- **%d file(s) with unresolved git conflict markers** — resolve and recommit:\n", len(hits))
		for _, h := range hits {
			fmt.Fprintf(&b, "  - %s:%d%s\n", h.Rel, h.Line, ownerSuffix(cfg, articleDomain(root, h.Rel)))
		}
	}

	// Staleness and contradiction findings deliberately do NOT appear
	// here: their ledgers are gitignored per-machine state, and a
	// committed digest built from them never converges across members.
	// They print as machine-local notes instead (digestLocalNotes).

	if findings == 0 {
		b.WriteString("Nothing outstanding.\n")
	}

	// --- Ownership ---
	if len(cfg.Owners) > 0 {
		b.WriteString("\n## Owners\n\n")
		domains := make([]string, 0, len(cfg.Owners))
		for d := range cfg.Owners {
			domains = append(domains, d)
		}
		sort.Strings(domains)
		for _, d := range domains {
			fmt.Fprintf(&b, "- %s → %s\n", d, cfg.Owners[d])
		}
		if unowned := unownedDomains(cfg); len(unowned) > 0 {
			fmt.Fprintf(&b, "\nUnowned domains: %s — add them to `owners:` in scribe.yaml so findings have a route.\n",
				strings.Join(unowned, ", "))
		}
	}

	return b.String()
}

// ownerFor returns the configured owner for a domain, "" when unowned.
func ownerFor(cfg *ScribeConfig, domain string) string {
	if cfg == nil || domain == "" {
		return ""
	}
	return cfg.Owners[domain]
}

// ownerSuffix renders the " — owner: X" tail for a finding line.
func ownerSuffix(cfg *ScribeConfig, domain string) string {
	if o := ownerFor(cfg, domain); o != "" {
		return " — owner: " + o
	}
	return ""
}

// unownedDomains lists configured domains with no owners entry.
func unownedDomains(cfg *ScribeConfig) []string {
	if cfg == nil {
		return nil
	}
	var out []string
	for _, d := range cfg.Domains {
		if cfg.Owners[d] == "" {
			out = append(out, d)
		}
	}
	sort.Strings(out)
	return out
}

// articleDomain reads the domain: frontmatter of a KB-relative article
// path; "" when unreadable.
func articleDomain(root, rel string) string {
	data, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		return ""
	}
	fm, err := parseFrontmatter(data)
	if err != nil || fm == nil {
		return ""
	}
	return fm.Domain
}

// digestActivity is one contributor's article changes in the window.
type digestActivity struct {
	author  string
	added   []string
	updated []string
}

// digestWindowAnchor returns the committer date of the newest commit
// touching wiki content, with underscore machinery files excluded so
// digest/index regeneration commits don't move the window themselves.
func digestWindowAnchor(root string) (time.Time, bool) {
	args := make([]string, 0, 4+2*len(wikiDirs))
	args = append(args, "log", "-1", "--pretty=format:%cI", "--")
	for _, d := range wikiDirs {
		args = append(args, d, ":(exclude)"+d+"/_*")
	}
	out := strings.TrimSpace(runCmd(root, "git", args...))
	if out == "" {
		return time.Time{}, false
	}
	anchor, err := time.Parse(time.RFC3339, out)
	if err != nil {
		return time.Time{}, false
	}
	return anchor, true
}

// gitDigestActivity parses `git log --name-status` over the wiki dirs
// into per-author added/updated article lists. Underscore-prefixed
// files (indexes, ledgers, the digest itself) are excluded — they're
// machinery, not knowledge.
//
// The window is anchored to the last content commit, NOT the wall
// clock: "--since=7.days.ago" drifts daily, so every member's sync
// would regenerate a slightly different digest and commit the churn.
// Anchored, the digest is a pure function of committed history —
// identical bytes on every machine until a real article commit lands.
func gitDigestActivity(root string, days int) []digestActivity {
	anchor, ok := digestWindowAnchor(root)
	if !ok {
		return nil
	}
	args := make([]string, 0, 6+len(wikiDirs))
	args = append(args,
		"log", "--since="+anchor.AddDate(0, 0, -days).Format(time.RFC3339),
		"--pretty=format:%x01%an", "--name-status", "--no-renames", "--")
	args = append(args, wikiDirs...)
	out := runCmd(root, "git", args...)
	if out == "" {
		return nil
	}

	type fileSet struct {
		added   map[string]bool
		updated map[string]bool
	}
	byAuthor := map[string]*fileSet{}
	current := ""
	for line := range strings.SplitSeq(out, "\n") {
		line = strings.TrimRight(line, "\r")
		if rest, ok := strings.CutPrefix(line, "\x01"); ok {
			current = strings.TrimSpace(rest)
			continue
		}
		if current == "" || line == "" {
			continue
		}
		status, path, ok := strings.Cut(line, "\t")
		if !ok || !strings.HasSuffix(path, ".md") {
			continue
		}
		if strings.HasPrefix(filepath.Base(path), "_") {
			continue
		}
		fs := byAuthor[current]
		if fs == nil {
			fs = &fileSet{added: map[string]bool{}, updated: map[string]bool{}}
			byAuthor[current] = fs
		}
		switch {
		case strings.HasPrefix(status, "A"):
			fs.added[path] = true
		case strings.HasPrefix(status, "M"):
			fs.updated[path] = true
		}
	}

	authors := make([]string, 0, len(byAuthor))
	for a := range byAuthor {
		authors = append(authors, a)
	}
	sort.Strings(authors)

	result := make([]digestActivity, 0, len(authors))
	for _, a := range authors {
		fs := byAuthor[a]
		// A file both added and updated in the window counts as new.
		for f := range fs.added {
			delete(fs.updated, f)
		}
		act := digestActivity{author: a, added: sortedKeys(fs.added), updated: sortedKeys(fs.updated)}
		if len(act.added)+len(act.updated) > 0 {
			result = append(result, act)
		}
	}
	return result
}

// capList truncates a list for display, appending an ellipsis entry.
func capList(items []string, limit int) []string {
	if len(items) <= limit {
		return items
	}
	out := append([]string{}, items[:limit]...)
	return append(out, fmt.Sprintf("… and %d more", len(items)-limit))
}
