package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// HotCmd writes wiki/_hot.md — a 4-section single-file context cache that
// SessionStart(startup|resume) and PostCompact hooks inject into active
// Claude Code sessions. Deterministic, zero LLM calls.
//
// See decisions/hot-md-postcompact-hook.md for the adoption rationale.
type HotCmd struct {
	DryRun  bool `help:"Print what would be written without writing." name:"dry-run"`
	Install bool `help:"Install SessionStart + PostCompact hooks in ~/.claude/settings.json."`
}

func (h *HotCmd) Run() error {
	root, err := kbDir()
	if err != nil {
		return err
	}

	if h.Install {
		return installHotHooks(root)
	}

	content, err := generateHotMD(root)
	if err != nil {
		return fmt.Errorf("generate: %w", err)
	}

	if h.DryRun {
		fmt.Print(content)
		return nil
	}

	path := filepath.Join(root, "wiki", "_hot.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	logMsg("hot", "wrote %s (%d bytes)", path, len(content))
	return nil
}

// rollingEntry is one H2 heading parsed from a rolling memory file.
type rollingEntry struct {
	Project string
	Date    time.Time
	Title   string
	Kind    string // "decision" | "learning"
}

// h2DateRE matches rolling-file headings like "## 2026-04-10 | Title"
var h2DateRE = regexp.MustCompile(`^## (\d{4}-\d{2}-\d{2})\s*\|\s*(.+?)\s*$`)

// generateHotMD builds the 4-section context cache from recent rolling
// memory files. Everything is deterministic — filesystem scan, regex,
// string formatting. No LLM calls.
func generateHotMD(root string) (string, error) {
	projectsDir := filepath.Join(root, "projects")
	entries, err := os.ReadDir(projectsDir)
	if err != nil {
		return "", fmt.Errorf("read projects dir: %w", err)
	}

	cutoff := time.Now().AddDate(0, 0, -7)
	var decisions, learnings []rollingEntry
	latestPerProject := make(map[string]time.Time)

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pname := e.Name()
		projDir := filepath.Join(projectsDir, pname)

		for _, spec := range []struct {
			filename string
			kind     string
			sink     *[]rollingEntry
		}{
			{"decisions-log.md", "decision", &decisions},
			{"learnings.md", "learning", &learnings},
		} {
			ents, err := scanRollingFile(projDir, pname, spec.filename, spec.kind)
			if err != nil {
				continue
			}
			for _, ent := range ents {
				if !ent.Date.Before(cutoff) {
					*spec.sink = append(*spec.sink, ent)
					if t, ok := latestPerProject[pname]; !ok || ent.Date.After(t) {
						latestPerProject[pname] = ent.Date
					}
				}
			}
		}
	}

	sort.Slice(decisions, func(i, j int) bool { return decisions[i].Date.After(decisions[j].Date) })
	sort.Slice(learnings, func(i, j int) bool { return learnings[i].Date.After(learnings[j].Date) })

	type threadInfo struct {
		project string
		date    time.Time
	}
	var threads []threadInfo
	for p, t := range latestPerProject {
		threads = append(threads, threadInfo{p, t})
	}
	sort.Slice(threads, func(i, j int) bool { return threads[i].date.After(threads[j].date) })
	if len(threads) > 5 {
		threads = threads[:5]
	}

	// Build a per-project title lookup: most recent decision wins, learning as fallback.
	titleFor := make(map[string]string)
	for _, d := range decisions {
		if _, ok := titleFor[d.Project]; !ok {
			titleFor[d.Project] = d.Title
		}
	}
	for _, l := range learnings {
		if _, ok := titleFor[l.Project]; !ok {
			titleFor[l.Project] = l.Title
		}
	}

	// Open questions: learnings whose title contains a literal '?',
	// starts with "TODO", or contains "open question".
	var openQs []rollingEntry
	for _, l := range learnings {
		lower := strings.ToLower(l.Title)
		if strings.Contains(l.Title, "?") ||
			strings.HasPrefix(lower, "todo") ||
			strings.Contains(lower, "open question") {
			openQs = append(openQs, l)
		}
	}

	var buf strings.Builder
	buf.WriteString("# Hot Cache\n\n")
	buf.WriteString("*Generated by `scribe hot`; overwritten on every sync and dream run. Do not edit by hand.*\n\n")

	buf.WriteString("## Active threads\n\n")
	if len(threads) == 0 {
		buf.WriteString("- No project activity in the last 7 days.\n")
	} else {
		for _, t := range threads {
			title := titleFor[t.project]
			if title == "" {
				title = "(no entry)"
			}
			fmt.Fprintf(&buf, "- **%s** (%s) — %s\n",
				t.project, t.date.Format("2006-01-02"), truncateUTF8(title, 80))
		}
	}
	buf.WriteString("\n")

	buf.WriteString("## Recent decisions\n\n")
	if len(decisions) == 0 {
		buf.WriteString("- No decisions logged in the last 7 days.\n")
	} else {
		limit := min(len(decisions), 3)
		for _, d := range decisions[:limit] {
			fmt.Fprintf(&buf, "- **%s** [%s] — %s\n",
				d.Date.Format("2006-01-02"), d.Project, truncateUTF8(d.Title, 100))
		}
	}
	buf.WriteString("\n")

	buf.WriteString("## Open questions\n\n")
	if len(openQs) == 0 {
		buf.WriteString("- None flagged in recent rolling memory.\n")
	} else {
		limit := min(len(openQs), 3)
		for _, q := range openQs[:limit] {
			fmt.Fprintf(&buf, "- **%s** [%s] — %s\n",
				q.Date.Format("2006-01-02"), q.Project, truncateUTF8(q.Title, 100))
		}
	}
	buf.WriteString("\n")

	buf.WriteString("## Last updated\n\n")
	fmt.Fprintf(&buf, "%s\n", time.Now().UTC().Format(time.RFC3339))

	return buf.String(), nil
}

func scanRollingFile(projDir, pname, filename, kind string) ([]rollingEntry, error) {
	path := filepath.Join(projDir, filename)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var results []rollingEntry
	for line := range strings.SplitSeq(string(data), "\n") {
		m := h2DateRE.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		date, err := time.Parse("2006-01-02", m[1])
		if err != nil {
			continue
		}
		results = append(results, rollingEntry{
			Project: pname,
			Date:    date,
			Title:   m[2],
			Kind:    kind,
		})
	}
	return results, nil
}

// truncateUTF8 clips a string to n runes without splitting a multi-byte char.
func truncateUTF8(s string, n int) string {
	runes := []rune(s)
	if len(runes) <= n {
		return s
	}
	if n < 4 {
		return string(runes[:n])
	}
	return string(runes[:n-3]) + "..."
}

// writeHotMDQuiet regenerates wiki/_hot.md without logging on success.
// Called from the end of sync and dream runs. Errors are logged but
// never propagated — a broken hot cache should never fail a sync.
func writeHotMDQuiet(root string) {
	content, err := generateHotMD(root)
	if err != nil {
		logMsg("hot", "skipped: %v", err)
		return
	}
	path := filepath.Join(root, "wiki", "_hot.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		logMsg("hot", "write failed: %v", err)
		return
	}
}

// installHotHooks writes SessionStart(startup|resume) and PostCompact entries
// into ~/.claude/settings.json. Idempotent — skips if the exact command
// is already present in a matching hook entry.
func installHotHooks(root string) error {
	home := os.Getenv("HOME")
	if home == "" {
		return fmt.Errorf("HOME not set")
	}
	settingsPath := filepath.Join(home, ".claude", "settings.json")
	hotPath := filepath.Join(root, "wiki", "_hot.md")
	cmd := "cat " + hotPath

	var settings map[string]any
	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parse %s: %w", settingsPath, err)
		}
	}
	if settings == nil {
		settings = make(map[string]any)
	}

	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = make(map[string]any)
	}

	startupEntry := map[string]any{
		"matcher": "startup|resume",
		"hooks": []any{
			map[string]any{"type": "command", "command": cmd},
		},
	}
	hooks["SessionStart"] = addHookIfMissing(hooks["SessionStart"], startupEntry, cmd)

	compactEntry := map[string]any{
		"hooks": []any{
			map[string]any{"type": "command", "command": cmd},
		},
	}
	hooks["PostCompact"] = addHookIfMissing(hooks["PostCompact"], compactEntry, cmd)

	settings["hooks"] = hooks

	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(settingsPath, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", settingsPath, err)
	}
	logMsg("hot", "installed hooks in %s", settingsPath)
	logMsg("hot", "run `scribe hot` once to populate %s", hotPath)
	return nil
}

// addHookIfMissing appends entry to existing if no entry with the same
// command is already present. Returns the new slice.
func addHookIfMissing(existing any, entry map[string]any, cmd string) []any {
	arr, _ := existing.([]any)
	for _, e := range arr {
		m, ok := e.(map[string]any)
		if !ok {
			continue
		}
		hookCmds, _ := m["hooks"].([]any)
		for _, hc := range hookCmds {
			hcMap, ok := hc.(map[string]any)
			if !ok {
				continue
			}
			if hcCmd, _ := hcMap["command"].(string); hcCmd == cmd {
				return arr
			}
		}
	}
	return append(arr, entry)
}
