package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// maxMentionsForIdentityPrompt caps the number of unmatched mentions we
// forward to the LLM. A busy KB can produce thousands of @handles and
// emails; feeding them all would blow the context window and make the
// clustering output noisy. 400 is enough to catch the frequent ones.
const maxMentionsForIdentityPrompt = 400

// runIdentitiesCheck harvests person-mentions across wiki + raw, compares
// them against existing people/*.md titles and aliases, and asks the LLM
// to cluster the unmatched surface forms. Output is proposal-only to
// wiki/_identity-proposals.md — a human decides which aliases to add or
// which new people pages to create.
func runIdentitiesCheck(outputMD string, dryRun bool) error {
	root, err := kbDir()
	if err != nil {
		return err
	}
	cfg := loadConfig(root)

	existing := collectExistingPeople(root)
	mentions := harvestMentions(root, existing)

	if len(mentions) == 0 {
		fmt.Println("no unmatched person-mentions found")
		return nil
	}

	logMsg("identities", "%d existing people pages, %d unmatched mention(s)", len(existing), len(mentions))

	if dryRun {
		for m, count := range mentions {
			fmt.Printf("  %s (×%d)\n", m, count)
		}
		return nil
	}

	outPath := outputMD
	if outPath == "" {
		outPath = filepath.Join(root, "wiki", "_identity-proposals.md")
	}

	peopleBlock := renderPeopleBlock(existing)
	mentionsBlock := renderMentionsBlock(mentions)

	prompt, err := loadPrompt("identities.md", map[string]string{
		"PEOPLE":   peopleBlock,
		"MENTIONS": mentionsBlock,
	})
	if err != nil {
		return err
	}

	provider := newLLMProvider(
		cfg.Absorb.Contextualize.Provider,
		cfg.Absorb.Contextualize.Model,
		cfg.Absorb.Contextualize.OllamaURL,
		root,
	)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	text, err := provider.Generate(ctx, prompt)
	if err != nil {
		return fmt.Errorf("%s: %w", provider.Name(), err)
	}
	text = strings.TrimSpace(text)

	header := fmt.Sprintf("# Identity proposals — scanned %s\n\nGenerated by `scribe lint --identities`. Review by hand; add `aliases:` to matching people pages or create new ones. Re-run to refresh.\n\n",
		time.Now().UTC().Format(time.RFC3339))
	if err := os.WriteFile(outPath, []byte(header+text+"\n"), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	logMsg("identities", "wrote %s", relPath(root, outPath))
	fmt.Println(text)
	return nil
}

// existingPerson holds the title + aliases of a people/*.md entry so the
// LLM prompt can show what identities already exist in the KB.
type existingPerson struct {
	PagePath string
	Title    string
	Aliases  []string
}

// collectExistingPeople walks people/*.md and returns their title +
// aliases. Skips files outside the `people/` dir (other wiki subsystems
// may have pages with type: person but we want the canonical location).
func collectExistingPeople(root string) []existingPerson {
	peopleDir := filepath.Join(root, "people")
	entries, err := os.ReadDir(peopleDir)
	if err != nil {
		return nil
	}
	var out []existingPerson
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		path := filepath.Join(peopleDir, e.Name())
		data, rErr := os.ReadFile(path)
		if rErr != nil {
			continue
		}
		fm, fErr := parseFrontmatter(data)
		if fErr != nil {
			continue
		}
		out = append(out, existingPerson{
			PagePath: filepath.Join("people", e.Name()),
			Title:    fm.Title,
			Aliases:  toStringSlice(fm.Aliases),
		})
	}
	return out
}

// knownIdentities returns a set of lowercased strings (titles + aliases)
// so the mention harvester can skip anything already accounted for.
func knownIdentities(people []existingPerson) map[string]bool {
	set := make(map[string]bool)
	for _, p := range people {
		if p.Title != "" {
			set[strings.ToLower(p.Title)] = true
		}
		for _, a := range p.Aliases {
			if a != "" {
				set[strings.ToLower(a)] = true
			}
		}
	}
	return set
}

// collectNonPersonTitles gathers titles and aliases from every wiki dir
// *except* people/. Used to prefilter proper-name regex hits that are
// actually pages about tools/projects/patterns ("Claude Code",
// "Phoenix LiveView", "Iron Law"). Without this filter the LLM spent
// ~1800 tokens-per-run rejecting wiki concepts it was never asked about.
func collectNonPersonTitles(root string) map[string]bool {
	set := make(map[string]bool)
	if err := walkArticles(root, func(path string, content []byte) error {
		// Skip the people/ dir — those are the ones we want to MATCH against,
		// not hide from the LLM.
		rel := relPath(root, path)
		if strings.HasPrefix(rel, "people/") {
			return nil
		}
		fm, err := parseFrontmatter(content)
		if err != nil || fm == nil {
			return nil //nolint:nilerr // skip unparseable frontmatter, continue walk
		}
		if fm.Title != "" {
			set[strings.ToLower(fm.Title)] = true
		}
		for _, a := range toStringSlice(fm.Aliases) {
			if a != "" {
				set[strings.ToLower(a)] = true
			}
		}
		return nil
	}); err != nil {
		logMsg("identities", "walk wiki for titles: %v", err)
	}
	return set
}

var (
	// emailRE matches RFC-ish email addresses. Deliberately conservative
	// to avoid pulling every "x@y" out of code blocks.
	emailRE = regexp.MustCompile(`\b[A-Za-z0-9._%+-]{2,}@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b`)

	// handleRE matches @handles. Requires at least 3 chars to skip noise
	// like @me / @we that show up in wiki prose.
	handleRE = regexp.MustCompile(`(?m)(?:^|\s)(@[A-Za-z0-9_]{3,30})\b`)
)

// harvestMentions walks wiki + raw articles and extracts email addresses,
// @handles, and proper-name candidates that do not match any existing
// title or alias. Returns a frequency map so rare-but-real mentions get
// fed to the LLM and noise gets filtered by count.
func harvestMentions(root string, existing []existingPerson) map[string]int {
	known := knownIdentities(existing)
	nonPerson := collectNonPersonTitles(root)
	cfg := mergeIdentityConfig(loadConfig(root).Identities)
	handleStop := toLowerSet(cfg.HandleStopwords)
	emailDomainStop := toLowerSet(cfg.EmailDomainStopwords)
	counts := make(map[string]int)

	eachMD := func(_ string, data []byte) {
		s := string(codeFenceRE.ReplaceAll(data, nil))
		for _, m := range emailRE.FindAllString(s, -1) {
			lc := strings.ToLower(m)
			if known[lc] {
				continue
			}
			if _, domain, ok := strings.Cut(lc, "@"); ok && emailDomainStop[domain] {
				continue
			}
			counts[m]++
		}
		for _, m := range handleRE.FindAllStringSubmatch(s, -1) {
			h := m[1]
			lc := strings.ToLower(strings.TrimPrefix(h, "@"))
			if known[strings.ToLower(h)] || handleStop[lc] {
				continue
			}
			counts[h]++
		}
		// Wikilinks to missing people pages. If the body references
		// `[[Lisa Chen]]` and neither an existing people/ page nor a
		// non-people wiki page has that title, it's almost certainly a
		// person we haven't cataloged yet. Far higher precision than
		// running a proper-name regex against free prose.
		for _, m := range wikilinkRE.FindAllStringSubmatch(s, -1) {
			target := strings.TrimSpace(m[1])
			lc := strings.ToLower(target)
			if known[lc] || nonPerson[lc] {
				continue
			}
			// Heuristic: target has to look like a name (two or more
			// capitalized words, no lowercase-led tokens, no CamelCase).
			if !looksLikePersonTarget(target) {
				continue
			}
			counts[target]++
		}
	}

	// Wiki articles (excludes _-prefixed meta files).
	if err := walkArticles(root, func(path string, data []byte) error {
		eachMD(path, data)
		return nil
	}); err != nil {
		logMsg("identities", "walk wiki for mentions: %v", err)
	}
	// Raw articles too — often where fresh names first appear.
	rawDir := filepath.Join(root, "raw", "articles")
	if entries, err := os.ReadDir(rawDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			path := filepath.Join(rawDir, e.Name())
			if data, rErr := os.ReadFile(path); rErr == nil {
				eachMD(path, data)
			}
		}
	}

	// Frequency floor. Proper-name noise dominates on mature KBs — "Iron
	// Law", "Oban Pro", "Phoenix LiveView" and similar tech compounds
	// aren't page titles but still look like proper names. Requiring 3+
	// occurrences cuts one-off stray capitalizations. Emails and @handles
	// bypass the floor because a single email often IS the only evidence
	// we have of someone.
	const bareNameFloor = 3
	filtered := make(map[string]int)
	for k, v := range counts {
		if strings.HasPrefix(k, "@") || strings.Contains(k, "@") {
			filtered[k] = v
			continue
		}
		if v >= bareNameFloor {
			filtered[k] = v
		}
	}
	return filtered
}

// camelCaseTokenRE matches a word that has a capital letter somewhere
// after its first character (AppSignal, LiveView, TypeScript, JavaScript).
// Human names — including Slavic / Central European names like Krišková,
// O'Brien, D'Angelo — never exhibit this. Cheapest reliable separator
// between "person name candidate" and "tech brand".
var camelCaseTokenRE = regexp.MustCompile(`[A-Z]\S*[a-z][A-Z]`)

// looksLikePersonTarget returns true when a wikilink target plausibly
// names a person. Requires ≥2 tokens, every token starts with a capital
// (no lowercase prepositions or verbs), no CamelCase or ALL-CAPS.
// Everything else is some project/feature name that happened to get a
// missing-page wikilink.
func looksLikePersonTarget(s string) bool {
	tokens := strings.Fields(s)
	if len(tokens) < 2 || len(tokens) > 4 {
		return false
	}
	for _, tok := range tokens {
		if tok == "" {
			return false
		}
		if !isUpperLetter(rune(tok[0])) {
			return false
		}
		if strings.ToUpper(tok) == tok && len(tok) > 2 {
			return false // ALL-CAPS acronym token like "LLM"
		}
		if camelCaseTokenRE.MatchString(tok) {
			return false
		}
	}
	return true
}

func isUpperLetter(r rune) bool {
	return r >= 'A' && r <= 'Z'
}

// renderPeopleBlock serializes the existing people list for the prompt.
func renderPeopleBlock(people []existingPerson) string {
	if len(people) == 0 {
		return "(none)"
	}
	var lines []string
	for _, p := range people {
		line := fmt.Sprintf("- %s (%s)", p.Title, p.PagePath)
		if len(p.Aliases) > 0 {
			line += " — aliases: " + strings.Join(p.Aliases, ", ")
		}
		lines = append(lines, line)
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}

// renderMentionsBlock serializes harvested mentions for the prompt, sorted
// by frequency desc so the LLM focuses on high-signal entries. Truncates
// at maxMentionsForIdentityPrompt.
func renderMentionsBlock(counts map[string]int) string {
	type kv struct {
		k string
		v int
	}
	var pairs []kv
	for k, v := range counts {
		pairs = append(pairs, kv{k, v})
	}
	sort.Slice(pairs, func(i, j int) bool {
		if pairs[i].v != pairs[j].v {
			return pairs[i].v > pairs[j].v
		}
		return pairs[i].k < pairs[j].k
	})
	if len(pairs) > maxMentionsForIdentityPrompt {
		pairs = pairs[:maxMentionsForIdentityPrompt]
	}
	lines := make([]string, 0, len(pairs))
	for _, p := range pairs {
		lines = append(lines, fmt.Sprintf("- %s (×%d)", p.k, p.v))
	}
	return strings.Join(lines, "\n")
}
