package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// maxPairContentBytes caps how much of each article body is forwarded to
// the resolver LLM. Frontmatter is always included verbatim because the
// authority/updated/confidence fields are load-bearing; bodies are
// truncated to avoid blowing the context window on long articles.
const maxPairContentBytes = 6_000

// runResolveContradictions reads `wiki/_contradictions.md` (produced by
// `scribe lint --contradictions`), pulls the paired article paths out of
// each finding, loads frontmatter + truncated body for each, and asks
// the contextualize provider to pick a winner per pair. Output is written
// to `wiki/_resolution-proposals.md` for human review — we never
// auto-apply supersedes.
//
// Skips pairs where either article can't be read. Returns early with a
// friendly message if no _contradictions.md exists yet.
func runResolveContradictions(outputMD string, dryRun bool) error {
	root, err := kbDir()
	if err != nil {
		return err
	}

	contraPath := filepath.Join(root, "wiki", "_contradictions.md")
	data, err := os.ReadFile(contraPath)
	if err != nil {
		return fmt.Errorf("no _contradictions.md — run `scribe lint --contradictions` first")
	}

	pairs := parseContradictionPairs(string(data))
	if len(pairs) == 0 {
		fmt.Println("no contradiction pairs found in _contradictions.md")
		return nil
	}
	logMsg("resolve", "loaded %d contradiction pair(s)", len(pairs))

	cfg := loadConfig(root)

	var sb strings.Builder
	included := 0
	for _, p := range pairs {
		aBytes, aErr := os.ReadFile(filepath.Join(root, p.A))
		bBytes, bErr := os.ReadFile(filepath.Join(root, p.B))
		if aErr != nil || bErr != nil {
			logMsg("resolve", "skipped pair (%s | %s): unreadable", p.A, p.B)
			continue
		}
		sb.WriteString("\n\n---\n\nPAIR: ")
		sb.WriteString(p.A)
		sb.WriteString(" | ")
		sb.WriteString(p.B)
		if p.Summary != "" {
			sb.WriteString("\nFinding: ")
			sb.WriteString(p.Summary)
		}
		sb.WriteString("\n\n### Article A: ")
		sb.WriteString(p.A)
		sb.WriteString("\n\n")
		sb.WriteString(truncateForPrompt(string(aBytes)))
		sb.WriteString("\n\n### Article B: ")
		sb.WriteString(p.B)
		sb.WriteString("\n\n")
		sb.WriteString(truncateForPrompt(string(bBytes)))
		included++
	}
	if included == 0 {
		fmt.Println("no resolvable pairs (all articles unreadable)")
		return nil
	}

	outPath := outputMD
	if outPath == "" {
		outPath = filepath.Join(root, "wiki", "_resolution-proposals.md")
	}

	if dryRun {
		logMsg("resolve", "would resolve %d pair(s) → %s", included, relPath(root, outPath))
		return nil
	}

	prompt, err := loadPrompt("resolve-contradictions.md", map[string]string{
		"PAIRS": sb.String(),
	})
	if err != nil {
		return err
	}

	provider := newLLMProvider(
		cfg.Absorb.Contextualize.Provider,
		cfg.Absorb.Contextualize.Model,
		cfg.Absorb.Contextualize.OllamaURL,
	)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	text, err := provider.Generate(ctx, prompt)
	if err != nil {
		return fmt.Errorf("%s: %w", provider.Name(), err)
	}
	text = strings.TrimSpace(text)

	header := fmt.Sprintf("# Resolution proposals — scanned %s\n\nGenerated by `scribe lint --resolve` from `_contradictions.md`. Review by hand; apply `status: superseded` where you agree. Re-run to refresh.\n\n",
		time.Now().UTC().Format(time.RFC3339))
	if err := os.WriteFile(outPath, []byte(header+text+"\n"), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	logMsg("resolve", "wrote %s (%d pair(s) reviewed)", relPath(root, outPath), included)
	fmt.Println(text)
	return nil
}

// contradictionPair is a single line from _contradictions.md once parsed.
type contradictionPair struct {
	A, B    string
	Summary string
}

// pairLineRE matches the shape the contradictions prompt emits:
// `[path/a.md | path/b.md] one-sentence summary`. Whitespace-tolerant.
var pairLineRE = regexp.MustCompile(`^\[\s*([^|\]]+?)\s*\|\s*([^|\]]+?)\s*\]\s*(.*)$`)

func parseContradictionPairs(body string) []contradictionPair {
	var out []contradictionPair
	for line := range strings.SplitSeq(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ">") {
			continue
		}
		m := pairLineRE.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		out = append(out, contradictionPair{
			A:       strings.TrimSpace(m[1]),
			B:       strings.TrimSpace(m[2]),
			Summary: strings.TrimSpace(m[3]),
		})
	}
	return out
}

func truncateForPrompt(s string) string {
	if len(s) <= maxPairContentBytes {
		return s
	}
	return s[:maxPairContentBytes] + "\n\n[…article truncated for resolver]"
}
